add filter and sort functionality
lmachens/game-ticker pull request #12
Opened 2021-07-22 13:07 UTC by webdevelukas

- Add possibility to filter matches by `gameId` and/or `username`
_Example: /matches?page=5&itemsPerPage=2&gameId=59156&username=monaOver9000_
- Matches are now been sorted by from the newest to the oldest

2021-07-22 13:14 UTC, webdevelukas commented on src/lib/router.ts
> +function getFilter(filterOptions: FilterProps) {
Maybe this function should be called `getMatchesFilter` and been placed in the `matches.ts` file.

2021-07-22 13:18 UTC, AlexisRoe requested changes
easy solution

2021-07-22 13:18 UTC, AlexisRoe commented on src/lib/router.ts
> +  }
What happens if the values are arrays?
```suggestion
  if (typeof gameId !== 'undefined' && !Array.isArray(gameId)) {
    filter.gameId = Number(gameId);
  }
  if (typeof username !== 'undefined' && !Array.isArray(username)) {
    filter.username = String(username);
  }
```

2021-07-23 06:18 UTC, webdevelukas commented
Closed in favor of changes in #11

2021-07-23 06:18 UTC, closed without merging